//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `acme.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <acme.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ValueFactory.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/InputStream.h>
#include <Ice/OutputStream.h>
#include <IceUtil/PopDisableWarnings.h>

#if defined(_MSC_VER)
#   pragma warning(disable:4458) // declaration of ... hides class member
#elif defined(__clang__)
#   pragma clang diagnostic ignored "-Wshadow"
#elif defined(__GNUC__)
#   pragma GCC diagnostic ignored "-Wshadow"
#endif

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 >= 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 10
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace
{

const ::IceInternal::DefaultValueFactoryInit<::Acme::BaseObject> iceC_Acme_BaseObject_init("::Acme::BaseObject");

const ::IceInternal::DefaultValueFactoryInit<::Acme::Brick> iceC_Acme_Brick_init("::Acme::Brick");

}

Acme::BaseObject::~BaseObject()
{
}

const ::std::string&
Acme::BaseObject::ice_staticId()
{
    static const ::std::string typeId = "::Acme::BaseObject";
    return typeId;
}

Acme::Brick::~Brick()
{
}

const ::std::string&
Acme::Brick::ice_staticId()
{
    static const ::std::string typeId = "::Acme::Brick";
    return typeId;
}

namespace Ice
{
}

#else // C++98 mapping

namespace
{

}

/// \cond INTERNAL
::IceProxy::Ice::Object* ::IceProxy::Acme::upCast(BaseObject* p) { return p; }

void
::IceProxy::Acme::_readProxy(::Ice::InputStream* istr, ::IceInternal::ProxyHandle< BaseObject>& v)
{
    ::Ice::ObjectPrx proxy;
    istr->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new BaseObject;
        v->_copyFrom(proxy);
    }
}
/// \endcond

/// \cond INTERNAL
::IceProxy::Ice::Object*
IceProxy::Acme::BaseObject::_newInstance() const
{
    return new BaseObject;
}
/// \endcond

const ::std::string&
IceProxy::Acme::BaseObject::ice_staticId()
{
    return ::Acme::BaseObject::ice_staticId();
}

/// \cond INTERNAL
::IceProxy::Ice::Object* ::IceProxy::Acme::upCast(Brick* p) { return p; }

void
::IceProxy::Acme::_readProxy(::Ice::InputStream* istr, ::IceInternal::ProxyHandle< Brick>& v)
{
    ::Ice::ObjectPrx proxy;
    istr->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new Brick;
        v->_copyFrom(proxy);
    }
}
/// \endcond

/// \cond INTERNAL
::IceProxy::Ice::Object*
IceProxy::Acme::Brick::_newInstance() const
{
    return new Brick;
}
/// \endcond

const ::std::string&
IceProxy::Acme::Brick::ice_staticId()
{
    return ::Acme::Brick::ice_staticId();
}

Acme::BaseObject::~BaseObject()
{
}

/// \cond INTERNAL
::Ice::Object* Acme::upCast(BaseObject* p) { return p; }

/// \endcond
::Ice::ObjectPtr
Acme::BaseObject::ice_clone() const
{
    ::Ice::Object* p = new BaseObject(*this);
    return p;
}

namespace
{
const ::std::string iceC_Acme_BaseObject_ids[2] =
{
    "::Acme::BaseObject",
    "::Ice::Object"
};

}

bool
Acme::BaseObject::ice_isA(const ::std::string& s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_Acme_BaseObject_ids, iceC_Acme_BaseObject_ids + 2, s);
}

::std::vector< ::std::string>
Acme::BaseObject::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&iceC_Acme_BaseObject_ids[0], &iceC_Acme_BaseObject_ids[2]);
}

const ::std::string&
Acme::BaseObject::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
Acme::BaseObject::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::Acme::BaseObject";
    return typeId;
#else
    return iceC_Acme_BaseObject_ids[0];
#endif
}

/// \cond STREAM
void
Acme::BaseObject::_iceWriteImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice(ice_staticId(), -1, true);
    ::Ice::StreamWriter< BaseObject, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
Acme::BaseObject::_iceReadImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    ::Ice::StreamReader< BaseObject, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}
/// \endcond

namespace
{
const ::IceInternal::DefaultValueFactoryInit< ::Acme::BaseObject> iceC_Acme_BaseObject_init("::Acme::BaseObject");
}

::Ice::ValueFactoryPtr
Acme::BaseObject::ice_factory()
{
    return ::IceInternal::factoryTable->getValueFactory(::Acme::BaseObject::ice_staticId());
}

/// \cond INTERNAL
void
Acme::_icePatchObjectPtr(BaseObjectPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = BaseObjectPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(BaseObject::ice_staticId(), v);
    }
}
/// \endcond

Acme::Brick::~Brick()
{
}

/// \cond INTERNAL
::Ice::Object* Acme::upCast(Brick* p) { return p; }

/// \endcond
::Ice::ObjectPtr
Acme::Brick::ice_clone() const
{
    ::Ice::Object* p = new Brick(*this);
    return p;
}

namespace
{
const ::std::string iceC_Acme_Brick_ids[3] =
{
    "::Acme::BaseObject",
    "::Acme::Brick",
    "::Ice::Object"
};

}

bool
Acme::Brick::ice_isA(const ::std::string& s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_Acme_Brick_ids, iceC_Acme_Brick_ids + 3, s);
}

::std::vector< ::std::string>
Acme::Brick::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&iceC_Acme_Brick_ids[0], &iceC_Acme_Brick_ids[3]);
}

const ::std::string&
Acme::Brick::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
Acme::Brick::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::Acme::Brick";
    return typeId;
#else
    return iceC_Acme_Brick_ids[1];
#endif
}

/// \cond STREAM
void
Acme::Brick::_iceWriteImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice(ice_staticId(), -1, false);
    ::Ice::StreamWriter< Brick, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
    BaseObject::_iceWriteImpl(ostr);
}

void
Acme::Brick::_iceReadImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    ::Ice::StreamReader< Brick, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
    BaseObject::_iceReadImpl(istr);
}
/// \endcond

namespace
{
const ::IceInternal::DefaultValueFactoryInit< ::Acme::Brick> iceC_Acme_Brick_init("::Acme::Brick");
}

::Ice::ValueFactoryPtr
Acme::Brick::ice_factory()
{
    return ::IceInternal::factoryTable->getValueFactory(::Acme::Brick::ice_staticId());
}

/// \cond INTERNAL
void
Acme::_icePatchObjectPtr(BrickPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = BrickPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(Brick::ice_staticId(), v);
    }
}
/// \endcond

namespace Ice
{
}

#endif
